# Generated by Django 3.0.8 on 2020-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create',
            name='Issues',
            field=models.CharField(choices=[('cleared', 'cleared'), ('pending', 'pending'), ('flagger', 'flagger')], max_length=200, null=True),
        ),
    ]
