# Generated by Django 3.0.8 on 2020-08-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200731_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200, null=True)),
                ('nic_number', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password1', models.CharField(max_length=100, null=True)),
                ('password2', models.CharField(max_length=100, null=True)),
                ('User_Roles', models.CharField(choices=[('admin', 'admin'), ('Data_Entry', 'Data_Entry')], max_length=200, null=True)),
            ],
        ),
    ]
