# Generated by Django 3.0.8 on 2020-08-10 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserCreated',
        ),
    ]
